// Generated by https://quicktype.io

export interface DataWithTables {
    id:            string;
    name:          string;
    locationTitle: string;
    busStop:       string;
    status:        string;
    title:         string;
    description:   string;
}

export enum BusStop {
    Florida = "Florida",
}
